### ISSUE TITLE
Take it easy

### ISSUE THREAD

**Issue by elkimek** [mynodebtc/mynode#196]
I'd like to suggest stop adding as many apps as possible and after merging Dojo just focus on fixing bugs and stability.

I have only issues with myNode lately and I can see the same across multiple channels. Not sure if it's just me but I feel this is getting out of hands and project becoming more like (as a familiar user mentioned), an AppStore.

One thing would be great to have and that's opt-in/out for apps from scratch before installing anything. Complexity is enemy of security and overall usability and not everyone want to have installed dozens softwares without an option.

Thanks.

**Comment by kkdao** [comment]
+100

**Comment by abhiShandy** [comment]
I completely agree with you. To add to that. We need to work on documentation, code readability, contribution guides so that interested techies can customize it to their own liking.

**Comment by tehelsper** [comment]
@elkimek I understand, and that has been the strategy for a while now. Most updated have been to either increase stability or increase visibility of various information to make support easier.

I still like the idea of "apps" on top of a Bitcoin full node so that users can use available, open source software in a secure and easy-to-use way. However, I do agree it needs to be simple and as error-proof as possible.

**Comment by tehelsper** [comment]
Closing. Bug fixes and stability were the focus and now a few new apps are being added.
