### ISSUE TITLE
I'd like to build a modifed image. Missing `mynode_release_tool` 

### ISSUE THREAD

**Issue by xavierfiechter** [mynodebtc/mynode#205]
I'd like to build a modifed image. I'm missing `mynode_release_tool`, which seems not open.

From the makefile:

`git clone git@github.com:mynodebtc/mynode_release_tool.git out/mynode_release_tool`

Could someobe share (eg. wiki, readme or an issue) how the maintainers build mynode from scratch?

Basically I'm going to contribute a bit of code cleanup and a switch to be able to install myNode on an SD card (w/o external USB drive).

**Comment by abhiShandy** [comment]
I recently wrote this page: https://github.com/mynodebtc/mynode/wiki/Alternate-ways-to-setup-myNode

**Comment by tehelsper** [comment]
@abhiShandy Thank you for that wiki page!

@xavierfiechter Yes, you are missing the release tool because that is private and used to create the official releases. There are many other options depending on what you want to do. I would suggest starting with the developer options and taking a look at this:

https://github.com/mynodebtc/mynode#developing-for-mynode

This will let you create an image as well.

**Comment by xavierfiechter** [comment]
Thanks, I will try the suggested solution from the wiki page.
