### ISSUE TITLE
Upgrade error from 0.1.51 to 0.2.08: Job for glances.service failed 

### ISSUE THREAD

**Issue by Smiggel** [mynodebtc/mynode#328]
Flashed a new SD card. Waited for the blockchain to be fully synced and then started the update:

> Setting up glances (3.1.0-1) ...
> Job for glances.service failed because the control process exited with error code.
> See "systemctl status glances.service" and "journalctl -xe" for details.
> invoke-rc.d: initscript glances, action "start" failed.
> ● glances.service - Glances
>    Loaded: loaded (/etc/systemd/system/glances.service; disabled; vendor preset: enabled)
>    Active: activating (auto-restart) (Result: exit-code) since Sat 2020-05-30 12:16:39 CDT; 76ms ago
>   Process: 2372 ExecStartPre=/usr/bin/is_not_shutting_down.sh (code=exited, status=1/FAILURE)
> dpkg: error processing package glances (--configure):
>  installed glances package post-installation script subprocess returned error exit status 1
> Errors were encountered while processing:
>  glances

systemctl status glances.service

> ● glances.service - Glances
>    Loaded: loaded (/etc/systemd/system/glances.service; disabled; vendor preset: enabled)
>    Active: activating (auto-restart) (Result: exit-code) since Sat 2020-05-30 12:20:33 CDT; 21s ago
>   Process: 2727 ExecStartPre=/usr/bin/is_not_shutting_down.sh (code=exited, status=1/FAILURE)
>

**Comment by Smiggel** [comment]
Got it fixed. Removed the package:

> sudo apt-get remove glances

Then ran:

> sudo apt-get update
> sudo apt-get upgrade

After that I was able to install glances without issues.

**Comment by temp69** [comment]
Did not wait for the node to fully sync, maby i should have done that?

I had trouble updating from the RP3 image with the glances package, I manually installed glances with this command from the official website:

`curl -L https://bit.ly/glances | /bin/bash`

Then I remove the glances package from the `mynode_post_upgrade.sh` script.

`$TORIFY apt-get -y install libatlas-base-dev libffi-dev libssl-dev python3-bottle`

Last thing todo was to change the startup script `/etc/systemd/system/glances.service` since the glances executable is in a different location now.

`ExecStart=/usr/local/bin/glances -w`

**Comment by martinschultzkristensen** [comment]
Hey,
I'm trying to upgrade from Version | 0.1.51 |  to  Version | 0.2.19, following the "Upgrading your myNode" guide. I get following error:

`code 404, message File not found`
`"GET /mynode_rootfs_raspi3.tar.gz HTTP/1.1" 404 -`

MyNode hardware (please complete the following information):

Device: Raspi3
Version: 0.1.51

I've searched quite a long time for anyone with same issue. This seems like a related issue somehow. Please help! Thanks.

**Comment by tehelsper** [comment]
Support for Raspi 3 has been deprecated. I would recommend either sticking with v0.1.51 or upgrading to use a Raspberry Pi 4.
