### ISSUE TITLE
Shortening the time for updating apps

### ISSUE THREAD

**Issue by abhiShandy** [mynodebtc/mynode#383]
Currently, many apps are updated by the following process:
1. Delete its folder
2. Download the latest tarball and extract it
3. Install the app from source

Instead of that, if we pull the git repo and checkout to the latest tag, we might save a lot of time. Incremental updates like this will especially avoid reinstalling node packages (like in RTL, thunderhub).

I believe, saving time will not only increase the uptime of the node but also improve the user experience.

**Comment by tehelsper** [comment]
I agree about the time, but I am concerned about the increased complexity. Issues that arise due to upgrades, can no longer easily be solved by a reinstall.

I'm open to ideas, but I'd prefer to limit additional complexity.

Also, the time cost only needs to be paid once per upgrade, so someone upgrading every 2-3 months pays the cost once even if several upgrades had occurred. I'm also expecting upgrades to slow over time and I'd expect any benefit to decrease over time.

**Comment by abhiShandy** [comment]
You current method of using `.<APP>_url` file both as a flag for reinstalling and for saving the current version is quite neat. Switching to something else will need custom commands for every app. Commands for node packages might be similar, but I understand your concern for increased complexity.

I agree with the plan to reduce the frequency of updates (maybe fix it to a fortnight or monthly schedule). It will reduce the chances of bugs creeping in (before automated tests are setup).
