### ISSUE TITLE
myNode 0.2.14 - Specter not creating wallets

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#395]
I upgraded to version 0.2.14.

Specter shows (Green status) 
It showed existing devices.
Wallets were missing.
I tried to create both SingleSing and MultiSig both gave error.
Then I re-installed Specter from settings
Still same error. See screenshot

![image](https://user-images.githubusercontent.com/54225190/90337569-ef70f280-e000-11ea-9d55-f92518b0180d.png)

**Comment by tehelsper** [comment]
@ben-kaufman Any ideas? I have not run across this issue.

**Comment by ben-kaufman** [comment]
@imacfan is there any chance that your node is still syncing?
https://github.com/cryptoadvance/specter-desktop/issues/287 this seems like the same issue.
I'm pretty sure that the problem is that the call to Bitcoin Core for creating the wallet is timing out, but if it's not due to syncing I'll need to check what else could it be...

**Comment by imacfan** [comment]
> I'm pretty sure that the problem is that the call to Bitcoin Core for creating the wallet is timing out, but if it's not due to syncing I'll need to check what else could it be...

Yes, node synching fine.. lightning connected to it and all others apps on mynode are working fine.

![image](https://user-images.githubusercontent.com/54225190/90469397-56dc8e80-e136-11ea-89f0-9beae97c3c83.png)
