### ISSUE TITLE
tag not correct

### ISSUE THREAD

**Issue by xCaCO3** [mynodebtc/mynode#456]
Looks like v0.2.21 is not tagged/comitted correctly....

**Comment by xxi000000** [comment]
Is this why upgrading to v0.2.21 doesn't seem to do anything? I've tried both automatic and manual upgrades, and after both it still says it's running v0.2.20.

**Comment by SatoshiNakamotogmx** [comment]
ETH/SATS? OR BTC what project?

On Jan 4, 2021 12:32 PM, "XXI" <notifications@github.com> wrote:

Is this why upgrading to v0.2.21 doesn't seem to do anything? I've tried
both automatic and manual upgrades, and after both it still says it's
running v0.2.20.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mynodebtc/mynode/issues/456#issuecomment-754202051>, or
unsubscribe

**Comment by tehelsper** [comment]
Ah yeah, it's off by one. I updated the "latest_release" tag to jump to the tip so it will include the change in the version number and changelog.

**Comment by xxi000000** [comment]
That fixed it. Thanks!
