### ISSUE TITLE
Bitcoin whitepaper on node (with tor link to download)

### ISSUE THREAD

**Issue by Jacksper13** [mynodebtc/mynode#463]
It would be great if the bitcoin whitepaper was hosted on the SD or the HDD/SSD.

Ideally: 

- It would be viewed/opened/downloaded via button in the GUI
- Would have a tor link to it (premium feature?) to be able to share with any third party for them to download it from your node (ideally without giving them access to the node itself)

- [x] Mark this if you searched the existing list of open/closed issue and did not find anything similar

**Comment by tehelsper** [comment]
Apparently, already available via CLI.

https://www.reddit.com/r/Bitcoin/comments/l2192y/a_script_to_download_the_bitcoin_whitepaper_from/

bitcoin-cli getrawtransaction 54e48e5f5c656b26c3bca14a8c95aa583d07ebe84dde3b7dd4a78f4e4186e713 true |
  jq -r '.vout[].scriptPubKey.asm' | cut -c3- |
  xxd -p -r | tail +9c | head -c 184292 > bitcoin.pdf

**Comment by Jacksper13** [comment]
Cool! Then maybe a GUI button that runs that script in the Bitcoin menu? Was thinking of something easily accessible for non-techies =)

**Comment by SatoshiNakamotogmx** [comment]
Yes I have the white paper in a registered letter sent to myself and Postscript proof of my personal hijacked device ?  the First 0-49 and ..  explain to me exactly what you want me to do?  I unplugged when they hijacked my P2p and called me a bum.  I replied No u r.  I have their data as well Mac .  My keys and data have never been only my last time on was Jan 9 5:49 am.  They told me they would take care of all the writing...

**Comment by SatoshiNakamotogmx** [comment]
How is the non tech going to protect it self from this ?  BlueBorne (security vulnerability).  
blueborne vector


Web
Images
Videos
News

Any time

All regions

Filter: Moderate

BlueBorne (security vulnerability)
BlueBorne is a type of security vulnerability with Bluetooth implementations in Android, iOS, Linux and Windows. It affects many electronic devices such as laptops, smart cars, smartphones and wearable gadgets. One example is CVE-2017-14315. The vulnerabilities were first reported by Armis, an IoT security firm, on 12 September 2017. According to Armis, "The BlueBorne attack vector can potentially affect all devices with Bluetooth capabilities, estimated at over 8.2 billion devices today [2017]."
Wikipedia.  This is something I know because I been a victim besides the hijacking of my email address and p2p in 2011 I got data for that ...

**Comment by SatoshiNakamotogmx** [comment]
> "How is the non tech going to protect it self from this ?  BlueBorne (security vulnerability).  
> blueborne vector
> 
> BlueBorne (security vulnerability)
> BlueBorne is a type of security vulnerability with Bluetooth implementations in Android, iOS, Linux and Windows. It affects many electronic devices such as laptops, smart cars, smartphones and wearable gadgets. One example is CVE-2017-14315. The vulnerabilities were first reported by Armis, an IoT security firm, on 12 September 2017. According to Armis, "The BlueBorne attack vector can potentially affect all devices with Bluetooth capabilities, estimated at over 8.2 billion devices today [2017]."
> Wikipedia.  This is something I know because I been a victim besides the hijacking of my email address and p2p in 2011 I got data for that ...
> 
> Put your stuff in a cold wallet.

**Comment by Jacksper13** [comment]
Looks like it's been added at f7d41729ca39bef9bdd312e5085578c5a0470136
