### ISSUE TITLE
Comparison with Umbrel: MyNode has no useful Bitcoin Wallet

### ISSUE THREAD

**Issue by StevenBlack** [mynodebtc/mynode#466]
One of the really nice things about [Umbrel](https://getumbrel.com) is it comes with a pretty nice Bitcoin wallet that's very quick to set up and use.  After my Umbrel's IBD it took a couple of minutes to experience immediate benefits of running local node.

In contrast, MyNode presents a bunch of apps, many of which have lengthy installation processes (if the installation works at all — see Issue #465) and evidently no app, like a simple Bitcoin wallet, the user can use immediately.

**Describe the solution you'd like**

MyNode should come bundled with a simple Bitcoin wallet, something immediately useful.  Because at the moment, after installing MyNode and allowing for a lengthy IBD, what can you do with a MyNode that you can't do with a blockchain explorer or mempool.space websites?  Answer: not much.

I think MyNode needs something that "pops", soon after IBD.  I don't consider setting up a Lightning service to be a "pop" kind of experience for most users.

**Comment by raymonddurk** [comment]
Agree that it would be a nice feature but it is a node. It isn't supposed to send transactions it is supposed to validate the blockchain. You can pair a lot of wallets with it or use things like RTL on MyNode already.

**Comment by StevenBlack** [comment]
> It isn't supposed to send transactions it is supposed to validate the blockchain.

Says who??  That makes zero sense whatsoever Raymond @raymonddurk.  What is this, then?  it says, "Lighning Wallet", right on the tile.

![2021-01-25_17-12-29](https://user-images.githubusercontent.com/80144/105772743-a5d1ef80-5f30-11eb-8daf-a95840337982.jpg)

I'm telling you, straight up: one of the things that makes Umbrel really nice, and a MUCH better experience than myNode, is it comes bundled with a full feature wallet that that you can use right away.

Since I've had these nodes I've onboarded three new Bitcoiners and I've used Umbrel for all three because here's a Bitcoin wallet that's rock solid, shows well on a Zoom call, has a fee slider to demonstrate that facet, and I can put a few sats in it for the demo and transfer out to the neocoiners.  It's beautiful.

I've had myNode up for a week and there's fuck all I can do with it because myNode isn't anything like Bitcoin node, it's a more lightning node because, it's all about Lightning.

I've got two nodes here, side by side.  At this rate, I'm just going to give the myNode away because it just doesn't cut mustard.  I'll wait for the next version to fix what's broken (see #465) but, at the moment, Ubrel wins by a fair margin, despite its particular shortcomings.

**Comment by tehelsper** [comment]
I agree there is no obvious "first thing" to do after myNode syncs, but I definitely DO NOT want it to be a Bitcoin wallet outside of Lightning (think cash in physical wallet, relatively limited).

Serious funds should not be stored in a device connected to the internet and especially one that is running so many services and apps. I do not want the keys controlling Bitcoin stored on the device and it was designed that way. I also did not want to build another wallet - there are many options out there and several are included within myNode for managing the Bitcoin/Lightning wallet used by LND (RTL, LND Hub, Thunderhub, etc...).

That is why I designed myNode to be the hub. It has a copy of the blockchain and numerous APIs / services to enable privacy for other apps to control the keys to larger Bitcoin wallets via Electrum, Specter, Caravan. That way the keys can be stored on hardware wallets, but you get the privacy advantages provided by using your own node and not a random one on the Internet or controlled by a target-rich company, like Ledger.

myNode may appear Lighting focused, and it is to some extent, but that is primarily because of the difference in Lightning vs Bitcoin apps.
Lightning = Actions, Send / Receive, Manage Wallets
Bitcoin = Services, Host blockchain data, Serve Electrum clients, passive mixing

The feature set is pretty close to 50/50 and much of the Lighting apps are various wallet options, which just depends on the user's preference.

**Comment by tehelsper** [comment]
@StevenBlack 

"Since I've had these nodes I've onboarded three new Bitcoiners and I've used Umbrel for all three because here's a Bitcoin wallet that's rock solid, shows well on a Zoom call, has a fee slider to demonstrate that facet, and I can put a few sats in it for the demo and transfer out to the neocoiners. It's beautiful."

If that is the case - why are they using a dedicated device? You can get all that with a simple Electrum wallet on a PC or Blue Wallet on their phone and not need $100s of dollars worth of hardware. I doubt that type of user cares about running a node or the advantages of a local copy of the blockchain. I'm missing something about that type of user / use case.

**Comment by Jacksper13** [comment]
> Serious funds should not be stored in a device connected to the internet and especially one that is running so many services and apps. I do not want the keys controlling Bitcoin stored on the device and it was designed that way.

Agreed on the wallet side, any issue with any of the apps that ends up risking user funds would mean the end of this project. To @StevenBlack's point though, I do think Umbrel has some UI wins that could "easily" be imported to myNode (maybe this should be a different issue?), for example:

 - Umbrel lets you mess around while the IBD is ongoing, while myNode blocks every interaction until it is finished. This going from 0 to 100 after the IBD is not the smoothest transition, people can get overwhelmed with options they don't necessarily understand after the IBD is done with. 

 - In relation to understanding what things are, Umbrel has a brief explanation of what each app does. I for one had no clue what in the world "electrum server" was when I first plugged my myNode, why it was disabled by default, or why it was needed for other stuff to work. A quick proposal would be that when you get to the main menu (ideally while the IBD is happening), each option has a familiar 
![image](https://user-images.githubusercontent.com/63911988/105830263-95b81f80-5fc5-11eb-8696-b6a5ee1db812.png) icon on the top right corner of their app area that you can click for a brief description of what it is, how it interacts with other apps and why you would want to enable/disable them. I would add that this icon should be able to be displayed/hidden on demand, by adding a "Show/Hide Help" button with the same question mark icon on the top right corner of the main menu, side by side with the "Use HTTPS", "Logout" and "Shutdown/reboot" options. This should be enabled by default, would give newcomers a better understanding of what each app does and advanced users could easily disable it to hide the icons. It would also be great if this brief description showed the estimated times with HDD and SSD (way too many people ask in the telegram groups if their Electrum is taking too long to download or compress)

- Pretty moving things! Umbrel has these rotating cubes in the IBD that are useless at best, but as a level 2 monkey I enjoy seeing things move, it provides a feeling of progress that numbers alone don't. Maybe something cool would be to have the dropdown option for Bitcoin enabled by default while the IBD happens (screenshot below) and seeing the blocks show up there and push every other block to the right, with a satisfying disappearing green check when they get validated (like Umbrel does) with a completion % on the bitcoin menu where the difficulty and all that stuff lives once it's finished. Some other format of block that is not a yellow-orangeish square would also help

![image](https://user-images.githubusercontent.com/63911988/105831925-9ce02d00-5fc7-11eb-8ad4-82e5b1039892.png)

- App installation is way too easy on Umbrel, click and go. While the idea is pretty much the same in myNode, there are some hiccups, like with Dojo for example. When you first "Enable" it the goes "Installing" while the dockers get installed. After this is done though, you have to click "Install" again, which I would assume 100% of the people that enabled dojo would want to do, so maybe auto-trigger the installation so it is a true "one click" install? Not a big deal, but it makes the overall experience less smooth.

- Umbrell doesn't have this but mempool space does - a TV mode! I honestly just enjoy watching my node work. With the current panel I don't see much movement though, I have to scroll up and down and check each service - a TV mode that goes full screen with some charts and numbers would be fun, like current block and past blocks, mempool stats and a small graph, current difficulty level and a small trend chart, raspi temperature ram and cpu levels, a mini-graph of your LND channels with a table with the latest routings/sends/receives that gets updated in real time, some sort of pretty progress bars that get filled for whirlpool... Just spitting ideas out here, but something that could grab a tiny bit of all those apps that make myNode unique and be able to display it all in a single screen you could share with friends and show off haha.

**Comment by StevenBlack** [comment]
> Serious funds should not be stored in a device connected to the internet and especially one that is running so many services and apps. 

Totally agree.  Never did I have any intention of storing "serious funds" on this particular non-existant wallet.  Not having  a BTC wallet is a serious downer for myNode.  I have both running side-by-side.  I'm just saying, huge hole here.  Makes all the difference in the world.

A fair analogy, if I may:

Umbrel: "Here's a seat on the stock exchange."

myNode: "Here's a seat in the visitors gallery overlooking the stock exchange.  Behave yourself."

> If that is the case - why are they using a dedicated device? 

You misunderstand.  Here's the scenario.

* Zoom call
* Other end hods a Ledger Nano X they just initialized.  They are looking at their Ledger Live app on their phone.
* On screen I paste the address they sent me, I set the fee with the slider in Umbrel's wallet to a number on the very low-end of the next block showing on mempool.space.
* Hit send
* THREE SECONDS LATER dude at the other end of the Zoom call sees the $50 I just sent him and the confirmation count starting to slowly increment.

That's fucking magic, and that's what you get when you connect to the network directly with your own node.

I could have done the same with myNode, except it's a ridiculously buried procedure involving other devices, network connections to the myNode device, using beta features of whatever wallet I have.  Current state of the industry is this is all bespoke, hacky, difficult to set up, difficult to test, and when it works it's a huge relief (admit it!) because so much can go wrong.

Umbrel nails this perfectly.

**Comment by Jacksper13** [comment]
> I could have done the same with myNode, except it's a ridiculously buried procedure involving other devices, network connections to the myNode device, using beta features of whatever wallet I have. Current state of the industry is this is all bespoke, hacky, difficult to set up, difficult to test, and when it works it's a huge relief (admit it!) because so much can go wrong.

Haha I'm not sure I like the tone of the comment, let's try and keep it civilized and constructive.  

I don't have a strong opinion about the implementation of a wallet in myNode itself, but I honestly don't think that what you describe has any added value to sending the funds via samourai wallet, blue wallet or electrum (especially since it's you the one sending it and not the other end!). What you are saying is that sending magic internet money over a zoom call is awesome (which we all agree with =) ), but I think you are overestimating the advantages of sending them from a raspi vs sending them from a laptop or phone and underestimating the potential threats.

Can the connection to other wallets be more seamless? Sure. Could the UI be improved? By all means (https://github.com/mynodebtc/mynode/issues/466#issuecomment-767454608). Would adding a native wallet make the experience THAT MUCH better? I... am not positive.

**Comment by raymonddurk** [comment]
I still don't see why a node needs a built in wallet. I have written numerous Bitcoin Guides and I have tested many wallets with MyNode and that work. Ledger on Ledger Live, any hardware wallet on Specter, Blue Wallet, Zap, Samourai, Phoenix, Green Wallet, etc. all work when you connect MyNode to it. Ironically the only one I have ever had issues with is Electrum. If you are home, your laptop/desktop wallets can pair with your node on your home network. If you are out and about, you can still pair your wallet with certain apps. You certainly aren't walking around with Umbrel in your pocket so I don't see the point other than a nice to have. Umbrel is super user friendly, I recommend it all the time but a dedicated wallet is super far down the list of things I would ask for.

I am not sure what a zoom call has to do with anything but you can screenshare your node in the browser you are taking a call on. Ledger Live mobile doesn't have full node support if that is your concern? If you are trying to scan your friends ledger live over the screen you can still do that with any of the mobile wallets I listed above. Or turn on the encryption settings in zoom (it is off by default) and have your friend paste the address into zoom. 

Umbrel is pretty but I wouldn't call it MUCH better.

**Comment by StevenBlack** [comment]
I'm observing a stunning lack of vision here.

Not only should myNode provide a wallet, it should be open source, end-user extensible, and optionally API-driven.
