### ISSUE TITLE
www service kept failing after bitcoin.conf edit

### ISSUE THREAD

**Issue by xCaCO3** [mynodebtc/mynode#491]
www service was showing Bad gateway (nginx) after modifying bitcoin.conf file with (blockfilterindex=1).
Despite several restarts same issue. 

Looking at journalctl, www service was having issues with flask module (unrecognized). Tried to pip install flask / run mynode.py from cli, no cure. Narrowed down issue to env and then mynode.py needs python2.7 so edited www service script to use python2.7 and everything back to normal.

No idea, why this occurred, but it is resolved with this fix.

**Comment by rod-gp** [comment]
Hi, Seems I'm having the same problem after upgrade.. 
www.service - myNode Web Server
   Loaded: loaded (/etc/systemd/system/www.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-03-29 14:01:17 CDT; 2s ago
  Process: 5637 ExecStart=/usr/bin/python /var/www/mynode/mynode.py (code=exited, status=1/FAILURE)
 Main PID: 5637 (code=exited, status=1/FAILURE)

can you please help me to elaborate more on how you force it to python 2.7?

**Comment by xCaCO3** [comment]
for v.28 this worked:
do a "sudo /usr/bin/python2.7 /var/www/mynode/mynode.py" see if that brings up the website?
If this works, then just permanently edit the www.service file, and restart the service with systemctl

On the latest update more libs are messed up, so it took more bug fixing.

**Comment by tehelsper** [comment]
It sounds like something has happened that caused /usr/bin/python to start pointing at python3. I can easily make this change in the service file.

Can you run the following commands:

python -version
ls -lsa /usr/bin/python*

Did you do any manual changes to python or pip packages? I'm not sure how this reference would have changed.

**Comment by xCaCO3** [comment]
yes that's true. Updated the link, but qrcode mod cannot be found for some reason with the new update. (it was working prev.)

**Comment by rod-gp** [comment]
just checked and I have Python 2.7 ..  

I ran /usr/bin/python /var/www/mynode/mynode.py and the process is aborted due to a problem qrcode module not found. 

I ended up rolling back to version 	0.2.27 and everything worked fine.

**Comment by xCaCO3** [comment]
pip2 install qrcode resolved all issues now
