### ISSUE TITLE
Current Version and Latest Version	

### ISSUE THREAD

**Issue by HamishMacEwan** [mynodebtc/mynode#670]
The current terminology on http://mynode.local/apps/customize-app-versions is confusing.  IMHO, "current" and "latest" are almost synonyms, and which is the actually installed version isn't particularly clear.  "Current Version" might reasonably be interpreted to be the version currently installed, but this is not necessarily the case.  "Latest Version" (which may be anything but the latest version if you've customised to use an older version) is also consequently misleading.

If the term "Current Version" was used to describe the version currently used in the distribution version, and the term "Installed Version" to indicate, yes, the requested/installed version, this would make things much clearer.

**Comment by tehelsper** [comment]
So, the idea is that long-term apps may not auto-update if a new version is released. "Current" is intended to mean what's installed (maybe I can change to Installed Version) and "Latest" is intended to mean the newest available version. They do often match because apps auto-update.

I was thinking I could put the pin icon next to Latest if it has been customized. Would that help? What would help clarify?

**Comment by HamishMacEwan** [comment]
> I was thinking I could put the pin icon next to Latest if it has been customized. Would that help? What would help clarify?

Agree with the change to "Installed version" instead of "current" and if the Installed version is "pinned" add the pin icon.  Latest could then remain as the indicator of the version that would be installed if the pin were removed.

Thanks for the response.

**Comment by tehelsper** [comment]
No problem. It's been updated for next release.
