### ISSUE TITLE
Migration to PC mynode

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#862]
Is there a guide to migrate existing Raspberry pi 4 SSD to PC version of mynode. 

So the idea is that PC version should boot from thumb drive and detect the external SSD with existing data.

**Comment by tehelsper** [comment]
No guide specifically on that, but it will detect the existing drive. Some docker data will be lost when swapping between device types because it's specific to that architecture. Bitcoin and LND data should transfer seamlessly.

If you are swapping from one device type to another, I recommend starting fresh.

**Comment by imacfan** [comment]
Thanks !

I Only want Bitcoin data. LND is not activated. Just wanted to save on time. 

Also, on PC , external drive will work or it saves data on internal drive by only?
