### ISSUE TITLE
Mempool outdated

### ISSUE THREAD

**Issue by bucadoX** [mynodebtc/mynode#881]
I noticed that I have a mempool version of 2021 installed on my mynode:

![image](https://github.com/user-attachments/assets/ed1a3c41-12da-4249-b83c-9f39c4dd9a28)

This comes with several defects and broken functions. Why is the app not up to date and how can I change that?

I tried reinstalling the app, no luck.

Of course mynode is running the latest version.

**Comment by tehelsper** [comment]
The latest version of MyNode has version 3.0.0.

If you are still using a 32-bit OS, try upgrading to a newer image or newer device. Old OS/devices still have mempool v2.3.1.

**Comment by bucadoX** [comment]
Hi Taylor, thanks for the hint. According the status page I'm on 64-bit

![image](https://github.com/user-attachments/assets/1978aee8-e3ce-4bf2-844e-420985cb58d4)

Any other suggestion what might cause the issue?

**Comment by tehelsper** [comment]
Go to the application page and check for custom versions - you may have locked it. I have a device with those same specs running mempool 3.0.0 You could also try to re-flash the SD card to get onto the latest OS as well, which is bookworm rather than buster. If that doesn't work, try logging a support ticket and we can look more into the logs.

**Comment by bucadoX** [comment]
I noticed that on many other apps I have an old version. So most likley it's because I haven't updated the OS in ages...I'll fix that now, thanks!
